name: Build and deploy app

on:
  push:
    branches:
      - '**/*'

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Write line
        run: |
          echo hello world
